/* Shared project data: the single source for the homepage Work grid (leads only)
   and the Résumé page (full list). No build step: attaches to window.PROJECTS.
   Fields: id, name, type, typeLabel, status, wip, lede, tech, points[], card[],
   links[{t,h,i,d}], shots[], post{t,h}, lead (true = shown on the homepage). */
window.PROJECTS = [
  {id:'sanctumpdf',name:'SanctumPDF',type:'web',typeLabel:'Web app',status:'shipped',lead:true,
   lede:'Privacy-first PDF &amp; financial-file conversion, all in the browser.',
   tech:'Next.js · Tailwind · Supabase · Stripe · Vercel · Wasm: pdf-lib / pdf.js / QPDF',
   stack:['Next.js','Wasm','Supabase'],
   points:['<strong>Client-heavy, server-light.</strong> Wasm does the PDF work in-browser; the server only handles auth, payments and licence checks. Files live in memory and vanish on tab close.',
     '<strong>Avoided the AGPL trap.</strong> Chose pdf-lib + QPDF Wasm over Ghostscript/MuPDF, which cut the Wasm payload ~7&times; (&asymp;4MB &rarr; &asymp;580KB compressed) and removed a licensing landmine.',
     '<strong>14-locale i18n.</strong> SEO-driven internationalisation expanded the indexed surface from ~36 to 335+ pages.'],
   card:['<strong>Client-heavy, server-light.</strong> Wasm runs the PDF work in-browser; files live in memory and vanish on tab close.',
     '<strong>Avoided the AGPL trap.</strong> pdf-lib + QPDF Wasm cut the payload ~7&times; and removed a licensing landmine.'],
   links:[{t:'Visit site',h:'https://sanctumpdf.com',i:'i-globe'}],
   preview:'sanctum-preview.webp',
   shots:['sanctumpdf1.webp','sanctumpdf2.webp','sanctumpdf3.webp','sanctumpdf4.webp']},
  {id:'larshdev',name:'larsh.dev v2',type:'web',typeLabel:'Portfolio',status:'experiment',
   lede:'A front-end-heavy alternative take on this very site, built to show a different approach.',
   tech:'GSAP · Lenis · three.js · Archivo variable · self-hosted, no build step',
   points:['<strong>Motion as the medium.</strong> A GSAP and Lenis composition: a counter preloader, headline reveals animated character by character, a work gallery that scrolls sideways, and a marquee that reacts to scroll velocity, all on smooth scroll.',
     '<strong>An interactive three.js hero.</strong> A warm point-field wave that ripples under the cursor, held to a single low-power draw and thinned on small screens so the whole page stays light.',
     '<strong>One typeface, nothing left to chance.</strong> Archivo carries every weight from hairline to black against a single peach accent; fonts and libraries are self-hosted, so the page makes zero third-party calls and still honours <code>prefers-reduced-motion</code>.'],
   card:['<strong>Motion as the medium.</strong> A GSAP and Lenis composition on smooth scroll: counter preloader, character-by-character headline reveals, a sideways work gallery, a velocity-reactive marquee.',
     '<strong>Interactive three.js hero</strong> over one self-hosted typeface and a single accent; zero third-party calls, and it still honours <code>prefers-reduced-motion</code>.'],
   links:[{t:'View it',h:'experiment/',i:'i-globe'}],
   shots:['larshdev-1.webp']},
  {id:'swatch',name:'Swatch',type:'web',typeLabel:'Web app',status:'shipped',lead:true,
   lede:'A colour-palette studio: scroll bold palettes, then generate and export your own.',
   tech:'GSAP · Lenis · three.js · Clash Display · self-hosted, no build step',
   stack:['GSAP','Lenis','three.js'],
   points:['<strong>A stack you scroll through.</strong> Each palette is a full, oversized card that slides up and stacks over the last, its title, swatches and description built right into the card. The reveal is scroll-driven (CSS sticky + GSAP ScrollTrigger on Lenis), so it flows smoothly in both directions with no crossfade.',
     '<strong>Real colour, one click to copy.</strong> Every hex is selectable DOM text on a tile that animates internally only, never jumping the layout; a soft three.js wash of pastel light drifts behind the stack.',
     '<strong>Degrades without apology.</strong> Reduced-motion and no-JS fall back to a clean, fully accessible list of every palette; fonts and libraries are self-hosted, so the page makes zero third-party calls.'],
   card:['<strong>A stack you scroll through.</strong> Each palette slides up and stacks over the last, driven by CSS sticky + GSAP ScrollTrigger on Lenis.',
     '<strong>Real, copyable colour</strong> on tiles that animate internally only, over a soft three.js wash; falls back to a clean accessible list when motion is reduced.'],
   post:{t:'Building Swatch, or: a colour problem I gave myself',h:'blog/building-swatch-or-a-colour-problem-i-gave-myself.html'},
   links:[{t:'Visit site',h:'https://tryswatch.com',i:'i-globe'}],
   preview:'tryswatch-preview.webp',
   shots:['swatch-1.webp','swatch-2.webp']},
  {id:'metastrip',name:'MetaStrip',type:'web',typeLabel:'Web app',status:'shipped · open source',lead:true,
   lede:'Browser-based metadata removal: fully client-side, open source.',
   tech:'Next.js · 100% client-side · MIT · piexifjs / pdf-lib / jszip + custom binary parsers',
   stack:['Next.js','piexifjs','pdf-lib'],
   points:['<strong>Custom equal-size replacement for audio &amp; video.</strong> Hand-wrote an in-browser MP4 atom walker that swaps metadata atoms for <code>free</code> atoms of identical size, plus custom ID3/Vorbis/RIFF parsers replacing blocks with equal-length <code>PADDING</code>/<code>JUNK</code>. No length recomputation, no broken offset chains, playback never breaks.',
     '<strong>Structural privacy, not a promise.</strong> Zero upload, zero server, zero cache: verifiable in the Network tab. The guarantee is the architecture.',
     '<strong>Deliberate library-vs-custom split.</strong> Mature libs for the well-trodden image/PDF/Office paths; bespoke parsers only where byte-level control was required.'],
   card:['<strong>Equal-size metadata replacement.</strong> Hand-written MP4/ID3/Vorbis/RIFF parsers swap metadata for identical-length padding, so playback never breaks.',
     '<strong>Structural privacy, not a promise.</strong> Zero upload, zero server, zero cache: verifiable in the Network tab.'],
   post:{t:'The Bug That Only Existed in Spanish',h:'blog/the-bug-that-only-existed-in-spanish.html'},
   links:[{t:'Visit site',h:'https://metastrip.app',i:'i-globe'},{t:'Source',h:'https://github.com/lars-1987/metastrip',i:'i-github'}],
   preview:'metastrip-preview.webp',
   shots:['metastrip-1.webp','metastrip-2.webp','metastrip-3.webp']},
  {id:'fenced',name:'Fenced',type:'web',typeLabel:'Web app',status:'shipped · open source',
   lede:'Markdown to self-contained HTML: fully client-side, open source.',
   tech:'Vite + TypeScript · 100% client-side · MIT · markdown-it / Shiki (fine-grained, JS regex engine)',
   points:['<strong>Decoration that survives the clipboard.</strong> Syntax tokens render as inline styles and the window chrome runs on CSS custom properties, so every fenced block is portable, self-contained HTML. Copy one into a CMS or IDE and it keeps its look with zero stylesheet, no class names to carry along.',
     '<strong>Theme-aware terminals via <code>color-mix</code>.</strong> Each block derives its bar, border, and line-number shades from the chosen Shiki theme&rsquo;s own background and foreground, so a dark Catppuccin window stays correct on a light page. The same CSS is the single source shared by the live preview and the export.',
     '<strong>Lean by construction.</strong> Fine-grained Shiki imports plus the JavaScript regex engine drop the WASM blob and every unused grammar. Client-side throughout, nothing uploaded, cookieless analytics gated on DNT and GPC.'],
   card:['<strong>Decoration that survives the clipboard.</strong> Tokens as inline styles, chrome on CSS variables: portable, self-contained HTML.',
     '<strong>Theme-aware terminals via <code>color-mix</code>.</strong> Each block derives its shades from the chosen theme, so dark windows stay right on a light page.'],
   post:{t:'I built a whole tool to avoid formatting code blocks',h:'blog/i-built-a-whole-tool-to-avoid-formatting-code-blocks.html'},
   links:[{t:'Visit site',h:'https://fenced.dev',i:'i-globe'},{t:'Source',h:'https://github.com/lars-1987/fenced',i:'i-github'}],
   shots:['fenced1.webp']},
  {id:'atelier',name:'Atelier',type:'web',typeLabel:'Website design',status:'concept',lead:true,
   lede:'A boutique architecture studio site: design taste through restraint, with a fraction of the copy.',
   tech:'Single-file static site · Lenis smooth scroll · scroll-driven parallax + a pinned horizontal gallery · Fraunces + Inter Tight',
   stack:['Static site','Lenis','Fraunces'],
   points:['<strong>Taste through restraint.</strong> An architecture practice with roughly a fifth of the marketing copy of a typical brochure site: section labels, imagery and pacing carry the narrative instead of paragraphs. No testimonials, no pricing, no hard sell.',
     '<strong>Motion that earns its place.</strong> Lenis smooth scroll drives layered parallax, clip-path reveals and a gallery that pans sideways as you scroll down, ending on a footer the page lifts away to reveal. Custom reveal logic uses getBoundingClientRect so masks never break it.',
     '<strong>Built to a brief, not a template.</strong> One dependency-light HTML file that fully honours prefers-reduced-motion and degrades to native scroll: proof a distinctive brand can ship as a single fast page.'],
   card:['<strong>Taste through restraint.</strong> An architecture site that communicates with a fifth of the usual copy, letting imagery, labels and pacing carry it.',
     '<strong>Motion that earns its place.</strong> Lenis-driven parallax, clip-path reveals and a pinned horizontal gallery, ending on a card-lift footer.'],
   links:[{t:'View site',h:'atelier/',i:'i-globe'}],
   preview:'atelier-preview.webp',
   shots:['atelier.webp']},
  {id:'summit',name:'Summit',type:'web',typeLabel:'Website design',status:'concept',
   lede:'A local bike-workshop site built to earn trust: transparent pricing, real proof, strong local SEO.',
   tech:'Single-file static site · content-driven build · Archivo + Inter · schema.org BikeStore + FAQPage',
   points:['<strong>Trust as the whole strategy.</strong> For a local trade, credibility is the conversion: transparent fixed pricing, a 48-hour turnaround promise, specialist-brand signals and a 4.9-star review wall, all above the fold. A simple, well-built site is worth more to a bike mechanic than any ad spend.',
     '<strong>Long-tail SEO baked in.</strong> Keyword-targeted title and copy (&ldquo;premium bicycle servicing in Melbourne&rdquo;, &ldquo;Shimano &amp; SRAM specialists&rdquo;), a six-question FAQ and rich schema.org markup (BikeStore with services, pricing and aggregate rating, plus FAQPage) so it can rank for local intent.',
     '<strong>Conversion-focused build.</strong> Service cards pre-fill the booking form, a mobile sticky CTA follows the scroll and responsive WebP with srcset keeps it fast. One static file, no framework.'],
   card:['<strong>Trust as the whole strategy.</strong> Transparent pricing, a turnaround promise and a review wall, because credibility is the conversion for a local trade.',
     '<strong>Long-tail SEO baked in.</strong> Keyword-targeted copy, a six-question FAQ and BikeStore + FAQPage schema so it ranks for local intent.'],
   links:[{t:'View site',h:'summit/',i:'i-globe'}],
   shots:['summit.webp']},
  {id:'brighton',name:'Brighton',type:'web',typeLabel:'Website design',status:'concept',
   lede:'A cosmetic-dentistry site selling warmth, trust and luxury, where one Invisalign lead pays for it many times over.',
   tech:'Single-file static site · Cormorant Garamond + Inter · schema.org Dentist + FAQPage · before/after sliders',
   points:['<strong>Warmth, trust, luxury, by design.</strong> A boutique aesthetic-dentistry clinic where a warm cream-sage-bronze palette, editorial serif typography and a considered founder story do the selling. Calm pacing and consultation-only CTAs, no hard sell, for a high-value cosmetic audience.',
     '<strong>Proof that converts.</strong> Before/after sliders for veneers, Invisalign and bonding, a five-question FAQ answering the real objections (cost, pain, financing) and schema.org Dentist + FAQPage markup with a 4.9-star aggregate rating.',
     '<strong>The ROI case for good design.</strong> For a clinic where a single Invisalign case is worth thousands, a site that lifts trust and books one extra consultation pays for itself many times over: exactly the niche this build targets.'],
   card:['<strong>Warmth, trust, luxury, by design.</strong> Editorial serif type, a warm palette and a founder story sell a high-value cosmetic audience without a hard sell.',
     '<strong>Proof that converts.</strong> Before/after sliders, an objection-answering FAQ and Dentist + FAQPage schema with a 4.9-star rating.'],
   links:[{t:'View site',h:'brighton/',i:'i-globe'}],
   shots:['brighton.webp']},
  {id:'hawthorne',name:'Hawthorne',type:'web',typeLabel:'Website design',status:'concept',
   lede:'A boutique real-estate site that sells like a luxury magazine: editorial tone, hard numbers, trust.',
   tech:'Single-file static site · Cormorant Garamond + Inter · schema.org RealEstateAgent + FAQPage',
   points:['<strong>Editorial luxury for the inner east.</strong> A boutique agency selling $3&ndash;7.5M homes, positioned like a design publication: serif editorial typography, a restrained bronze-on-cream palette, lifestyle imagery and a conservative, no-aggressive-CTA tone that suits an affluent vendor.',
     '<strong>Numbers that do the persuading.</strong> Prominent proof: $750M+ sold, 94% clearance, 89% above reserve, 21 average days on market, plus a featured recent sale and vendor testimonials, structured for readers and search alike.',
     '<strong>The same trust playbook, different industry.</strong> Long-tail keyword targeting (&ldquo;luxury real estate in Hawthorn&rdquo;), a four-question appraisal FAQ and schema.org RealEstateAgent + FAQPage: a repeatable conversion system I can retarget per niche.'],
   card:['<strong>Editorial luxury for the inner east.</strong> A boutique agency for $3&ndash;7.5M homes, positioned like a design magazine: restrained, warm, conservative.',
     '<strong>Numbers that persuade.</strong> $750M+ sold, 94% clearance, 89% above reserve, with a featured sale and RealEstateAgent + FAQPage schema.'],
   links:[{t:'View site',h:'hawthorne/',i:'i-globe'}],
   shots:['hawthorne.webp']},
  {id:'renew',name:'Renew',type:'mobile',typeLabel:'Mobile app',status:'shipped',lead:true,
   lede:'Skincare tracking with real analytics and an OCR&rarr;AI label pipeline.',
   tech:'React Native · Expo · WatermelonDB · Supabase · OCR + Gemini',
   stack:['React Native','Expo','Gemini'],
   points:['<strong>OCR &rarr; Gemini extraction pipeline.</strong> Point the camera at a product; OCR lifts the text, Gemini parses it into structured INCI / brand / product data and translates Korean &amp; Japanese labels into a normalised, searchable form.',
     '<strong>Analytics as the differentiator.</strong> Skin-score trending, ingredient-conflict detection, and time-lagged correlation linking a breakout to something used days earlier.',
     '<strong>Offline-first by architecture.</strong> Longitudinal skin data lives in a local <strong>WatermelonDB</strong>, reactive, lazily-loaded, SQLite-backed, so logging is instant and works with no signal, then syncs to a Supabase backend as the cross-device source of truth.'],
   card:['<strong>OCR &rarr; Gemini extraction pipeline.</strong> Point the camera at a product; OCR and Gemini turn the label into structured INCI data, translating Korean &amp; Japanese into a searchable form.',
     '<strong>Offline-first by architecture.</strong> A local WatermelonDB makes logging instant with no signal, then syncs to Supabase as the source of truth.'],
   links:[{t:'Visit site',h:'https://getrenew.app',i:'i-globe'},{t:'App Store',h:'https://apps.apple.com/us/app/renew-skincare-tracker/id6758534567',i:'i-apple'}],
   preview:'renew-preview.webp',
   shots:['renew1.webp','renew2.webp','renew3.webp','renew4.webp','renew5.webp']},
  {id:'vesper',name:'Vesper',type:'mobile',typeLabel:'Mobile app',status:'shipped',
   lede:'Multilingual scripture app with a dynamic time-of-day sky system.',
   tech:'Expo · React Native · on-device SQLite · RevenueCat · no backend',
   points:['<strong>Two-database design.</strong> A read-only content DB (~94MB, four translations) cleanly separated from a user-data DB: shippable content distinct from user state.',
     '<strong>No backend, by design.</strong> Privacy plus zero infra cost, consistent across the portfolio.',
     '<strong>Dynamic sky system.</strong> Seven time-of-day phases cycle through the day: atmosphere and craft without a server.'],
   card:['<strong>Two-database design.</strong> A read-only ~94MB content DB (four translations) cleanly separated from a user-data DB.',
     '<strong>Dynamic sky system, no backend.</strong> Seven time-of-day phases cycle through the day: atmosphere and craft without a server.'],
   links:[{t:'Visit site',h:'https://tryvesper.app',i:'i-globe'},{t:'App Store',h:'https://apps.apple.com/us/app/vesper-daily-scripture/id6764037293',i:'i-apple'}],
   shots:['vesper1.webp','vesper2.webp','vesper3.webp','vesper4.webp']},
  {id:'virtus',name:'Virtus',type:'mobile',typeLabel:'Mobile app',status:'shipped',
   lede:'Stoic daily-wisdom and journaling: 150 passages, fully on-device.',
   tech:'Expo · React Native · RevenueCat · PostHog (cookieless) · no backend',
   points:['<strong>On-device content pipeline.</strong> A curated passage set with journaling prompts, shipped without any server dependency.',
     '<strong>Shared design system.</strong> The same architecture cleanly reskins into sibling apps: systematised, not copy-pasted.'],
   card:['<strong>On-device content pipeline.</strong> A curated passage set with journaling prompts, shipped with no server dependency.',
     '<strong>Shared design system.</strong> The same architecture cleanly reskins into sibling apps: systematised, not copy-pasted.'],
   links:[{t:'Visit site',h:'https://getvirtus.app',i:'i-globe'},{t:'App Store',h:'https://apps.apple.com/au/app/virtus-stoic-wisdom-journal/id6761154032',i:'i-apple'}],
   shots:['virtus1.webp','virtus2.webp','virtus3.webp']},
  {id:'bedcheck',name:'Bedcheck',type:'mobile',typeLabel:'Mobile app',status:'in development · alpha',wip:true,lead:true,
   lede:'An iOS accountability app for your bedtime, not your wake time.',
   tech:'Swift 6 (strict concurrency) · iOS 26 · SwiftUI + @Observable · SwiftData · AlarmKit · ActivityKit · WidgetKit · HealthKit · AppIntents',
   stack:['SwiftUI','SwiftData','AlarmKit'],
   points:['<strong>Built against AlarmKit on day one, before the docs existed.</strong> Read the <code>.swiftinterface</code> directly to verify API shapes; found Xcode silently drops <code>NSAlarmKitUsageDescription</code>, that <code>stopButton</code> was deprecated in 26.1, and that a missing Live Activity widget leaves alarms stuck as an empty Dynamic Island: all from device dogfooding.',
     '<strong>Three-rail reliability for the load-bearing feature.</strong> Local notifications + system-scheduled AlarmKit + a best-effort Live Activity. Each rail can fail without breaking the safety net; a documented "independence invariant" keeps any server roundtrip out of the alarm\'s critical path.',
     '<strong>Known limitations treated as decisions.</strong> A ~7,000-line spec before code, deviations tracked in a log, every accepted MVP failure mode documented with why it\'s acceptable and what fixes it in v1.1.'],
   card:['<strong>Built against AlarmKit before the docs existed.</strong> Read the <code>.swiftinterface</code> directly and surfaced silent Xcode bugs through device dogfooding.',
     '<strong>Three-rail reliability.</strong> Local notifications + AlarmKit + a Live Activity, each able to fail without breaking the safety net.'],
   links:[{t:'Visit site · coming soon',i:'i-globe',d:true},{t:'App Store · coming soon',i:'i-apple',d:true}],
   preview:'bedcheck-preview.webp',
   shots:['bedcheck1.webp','bedcheck2.webp']},
  {id:'helio',name:'Helio',type:'desktop',typeLabel:'Native macOS app',status:'in development',wip:true,
   lede:'A native macOS app for people juggling multiple long-running projects.',
   tech:'SwiftUI · SwiftData · CloudKit · Swift 6 (strict concurrency) · EventKit · macOS 14+',
   points:['<strong>The unit of work is the project, not the task.</strong> Task-first tools break for people running several long-running projects in parallel: the failure isn\'t forgetting a task, it\'s neglecting a whole project for weeks because re-loading the context feels insurmountable.',
     '<strong>A forced wind-down ritual closes every session.</strong> Structured capture of what got done, what\'s unfinished, and what\'s next, auto-loaded when you start the next session for that project.',
     '<strong>Getting the carry-forward chain right under CloudKit needed a non-obvious data model.</strong> A JSON blob breaks under last-write-per-field merge; the fix decomposes it into individual <code>PendingTask</code> CloudKit records, each with its own merge resolution, materialised atomically on next start.'],
   card:['<strong>The unit of work is the project, not the task.</strong> For people who lose weeks to a neglected project, not a forgotten task.',
     '<strong>A wind-down ritual ends every session.</strong> Captures done, unfinished, and next, auto-loaded when you resume.'],
   links:[{t:'Download · coming soon',i:'i-globe',d:true},{t:'App Store · coming soon',i:'i-apple',d:true}],
   shots:['helio1.webp','helio2.webp','helio3.webp']}
];
